import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;

/**
 *
 * @author ricky
 */
public class Messenger extends javax.swing.JFrame {

    /**
     * Creates new form Messenger
     */
    public Messenger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dispMessage = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        group1 = new javax.swing.JButton();
        group2 = new javax.swing.JButton();
        group3 = new javax.swing.JButton();
        group4 = new javax.swing.JButton();
        Send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dispMessage.setColumns(20);
        dispMessage.setRows(5);
        jScrollPane1.setViewportView(dispMessage);

        message.setColumns(20);
        message.setRows(5);
        jScrollPane2.setViewportView(message);

        group1.setText("Group 1");
        group1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group1ActionPerformed(evt);
            }
        });

        group2.setText("Group 2");
        group2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group2ActionPerformed(evt);
            }
        });

        group3.setText("Group 3");
        group3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group3ActionPerformed(evt);
            }
        });

        group4.setText("Group 4");
        group4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group4ActionPerformed(evt);
            }
        });

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        jLabel1.setText("displayMsg");

        jLabel2.setText("sendMsg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(group1)
                            .addComponent(group2)
                            .addComponent(group3)
                            .addComponent(group4)
                            .addComponent(Send))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(group1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(group2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(group3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(group4))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Send, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>                        
    int group;
    int flag=0;
    DatagramSocket socket;
    void sender(String s)
    {
       
        try
        {
        InetAddress destAddr = InetAddress.getByName("localhost");
        disp(destAddr.toString());
             //new DatagramSocket(6000);     
            byte send[]=new byte[1024];
            s=s+'x';
            send=s.getBytes();
            DatagramPacket packet=new DatagramPacket(send,send.length,destAddr,9876);
            socket.send(packet);
            //System.out.println(s);
            //disp(s);
        }
        catch(Exception e)
                {}
                
    }
    void setSocket()
    {
        try{
            //disp("check");
        socket = new DatagramSocket(6000); 
        //return socket;
        }
        catch(Exception e)
        {}
        //return null;
    }
    DatagramSocket getSocket()
    {
        return socket;
    }
    int getgroup()
    {
        return group;
    }
    int getFlag()
    {
        return flag;
    }
    private void group1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         group=1;
         flag=1;
        sender("group1");
    }                                      

    private void group2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        group=2;
        flag=1;
         sender("group2");
    }                                      

    private void group3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        group=3;
        flag=1;
         sender("group3");
    }                                      

    private void group4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        group=4;
        flag=1;
         sender("group4");
    }                                      

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String s=this.message.getText();
        this.message.setText("");
        //this.dispMessage.append();
        //disp(s);
        sender(s);
    }                                    
    void disp(String s)
    {
        this.dispMessage.append("me: "+s+"\n");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //Messenger m =new Messenger();
                new Messenger().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton Send;
    private javax.swing.JTextArea dispMessage;
    private javax.swing.JButton group1;
    private javax.swing.JButton group2;
    private javax.swing.JButton group3;
    private javax.swing.JButton group4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea message;
    // End of variables declaration                   
}
